name: Packaging and Pushing Artifactory for dotnet web App
on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  create-zip-file:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v5
      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Build and Publish app
        run: |
          pwd
          cd DemoWebApp/
          dotnet build
          dotnet publish --configuration Release --output ./publish/
      - name: Create Zip File
        run: |
          cd DemoWebApp/
          zip -r ../DemoApp.zip ./publish/
      - name: Upload Artifactory
        uses: actions/upload-artifact@v4
        with:
          name: DemoApp.zip
          path: DemoApp.zip

  publish-zip-file:
    needs: create-zip-file
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: DemoApp.zip
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            az storage blob upload --account-name storageaccountvmdemo1 --container blobdemo --name DemoApp.Zip --file DemoApp.zip --overwrite true


